server:
  port: 8270
  context-path: /log

spring:
    output:
        ansi:
            enabled: always
    jpa:
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
        show-sql: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://127.0.0.1:3306/dx_micro_base
        username: root
        max-idle: 10
        max-wait: 10000
        min-idle: 5
    rabbitmq:
        host: ${logmqhost:192.168.0.41}
        port: 5672
        username: 'guest'
        password: 'guest'

dingxin:
  core:
    system:
      permissionGen: false #是否开启权限数据自动生成
      permissionGenUri: http://localhost:8240/api/system/permission/gen
      contextPath: ${server.context-path}
logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

security:
    oauth2:
        resource:
            loadBalanced: true
            prefer-token-info: false
            service-id: dingxin-log-service
            user-info-uri: http://dingxin-api-gateway/api/uaa/user
    sessions: stateless

